SELECT TOP (1000) * FROM mytable

SELECT COLUMN_NAME, SUBSTRING(COLUMN_NAME,2, 3) as HEX
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'mytable' AND TABLE_SCHEMA='dbo' and column_name <> 'ts'
ORDER BY 2
