--RESTORE DATABASE bhp_aux WITH RECOVERY

SELECT 'RESTORE DATABASE [' + name + '] WITH RECOVERY ' FROM sys.databases 
WHERE 
	NAME NOT IN ('master', 'model','msdb','tempdb') 
ORDER BY 1;

/*

RESTORE DATABASE [Database1] WITH RECOVERY 
RESTORE DATABASE [Database2] WITH RECOVERY 
RESTORE DATABASE [Database3] WITH RECOVERY 
RESTORE DATABASE [Database4] WITH RECOVERY 
RESTORE DATABASE [Database5] WITH RECOVERY 

*/
